### ISSUE TITLE
Add localização dos simbolos na construção da classe do AST

### ISSUE THREAD

**Issue by danielferragut** [danielferragut/mc921-project1#29]
**Objetivo.**
No PR #28, foi implementado umas classes simples de AST pra terminais. Pra rodar no susy certo, precisa ter a localização também (o coord das classes). Ou seja precisa ter algo do tipo:

```
Program: 
    GlobalDecl: 
        Decl: ID(name='j'  )
            VarDecl:
                Type: ['int']   @ 2:1
            Constant: int, 3   @ 2:9
```
Ao invés de:
```
Program: 
    GlobalDecl: 
        Decl: ID(name='j'  )
            VarDecl:
                Type: ['int']   
            Constant: int, 3 
```
**Metas**
Implementar coordenadas pra ficar igual do susy.
